#!/usr/bin/env python3
"""Train a 784-64-10 MNIST MLP and export it as a C header for the firmware.

The generated header (default: Inc/mnist_weights.h) is consumed by
Src/app_mnist.c. Weights are stored as [out][in] float arrays, the output
layer produces logits (softmax is done on target).

Input preprocessing must match the firmware: pixels scaled to [0, 1],
white digit on black background, no mean/std normalization.

Usage:
    pip install tensorflow
    python python-scripts/mnist_train.py [--epochs 10] [--out Inc/mnist_weights.h]
"""

import argparse
from pathlib import Path

import numpy as np
import tensorflow as tf

REPO_ROOT = Path(__file__).resolve().parent.parent


def load_data():
    (x_tr, y_tr), (x_te, y_te) = tf.keras.datasets.mnist.load_data()
    x_tr = x_tr.reshape(-1, 784).astype("float32") / 255.0
    x_te = x_te.reshape(-1, 784).astype("float32") / 255.0
    return (x_tr, y_tr), (x_te, y_te)


def build_model():
    model = tf.keras.Sequential([
        tf.keras.Input((784,)),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(10),  # logits
    ])
    model.compile(optimizer="adam",
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=["accuracy"])
    return model


def c_values(a):
    flat = [f"{v:.8e}f" for v in a]
    return ",\n    ".join(", ".join(flat[i:i + 8]) for i in range(0, len(flat), 8))


def c_array(name, a):
    """1D or 2D float array as C initializer, 2D rows get their own braces."""
    if a.ndim == 1:
        body = f"    {c_values(a)}"
    else:
        body = ",\n".join(f"  {{\n    {c_values(row)}\n  }}" for row in a)
    dims = "".join(f"[{d}]" for d in a.shape)
    return f"static const float {name}{dims} = {{\n{body}\n}};\n\n"


def export_header(path, model, test_input, test_label):
    w1, b1 = model.layers[0].get_weights()  # Keras kernel is (in, out)
    w2, b2 = model.layers[1].get_weights()

    with open(path, "w") as f:
        f.write("/* Generated by python-scripts/mnist_train.py - do not edit */\n")
        f.write("#ifndef MNIST_WEIGHTS\n#define MNIST_WEIGHTS\n\n")
        f.write(c_array("mnist_w1", w1.T))  # [64][784]
        f.write(c_array("mnist_b1", b1))
        f.write(c_array("mnist_w2", w2.T))  # [10][64]
        f.write(c_array("mnist_b2", b2))
        # golden sample so the firmware can check its inference against Python
        f.write(c_array("mnist_test_input", test_input))
        f.write(f"#define MNIST_TEST_LABEL {int(test_label)}\n\n")
        f.write("#endif\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "Inc" / "mnist_weights.h")
    args = parser.parse_args()

    (x_tr, y_tr), (x_te, y_te) = load_data()
    model = build_model()
    model.summary()
    model.fit(x_tr, y_tr, epochs=args.epochs, batch_size=args.batch_size, validation_split=0.1)
    _, acc = model.evaluate(x_te, y_te, verbose=0)
    print(f"Test accuracy: {acc:.4f}")

    logits = model.predict(x_te[:1], verbose=0)[0]
    print(f"Golden sample: label {y_te[0]}, predicted {int(np.argmax(logits))}")

    export_header(args.out, model, x_te[0], y_te[0])
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
