/**
 ******************************************************************************
 * @file    imx219_isp_param_conf.h
 * @brief   ISP tuning parameters for the IMX219 sensor.
 *
 * Unlike imx335_isp_param_conf.h, this file was NOT generated by the STM32
 * ISP IQTune tool (that requires a real calibration pass -- color charts,
 * lux measurements -- against the actual IMX219 module and lens, which
 * wasn't available here). It's adapted from imx335_isp_param_conf.h instead.
 *
 * Fields adapted with confidence (derived from known IMX219 facts, not
 * guessed):
 *  - demosaicing.type: RGGB, matching the IMX219's default (no-flip) Bayer
 *    order (same as IMX335, so no change needed there, but confirmed
 *    correct independently -- see imx219.c's header comment).
 *  - statAreaStatic: recomputed for 1640x1232 (was 2592x1944), keeping the
 *    same "centered half" window convention (X0/Y0 = quarter, size = half).
 *  - luxRef HL_Expo2/LL_Expo2: use IMX219_EXPOSURE_MAX instead of IMX335's.
 *
 * Fields copied unchanged from IMX335 as a starting-point placeholder,
 * because they need real photometric/color calibration this repo has no way
 * to produce:
 *  - blackLevelStatic (BLCR/BLCG/BLCB): sensor-specific analog black offset.
 *  - AWBAlgo (illuminant gains/matrices/reference RGB): color calibration
 *    against this specific sensor+lens; colors will likely be off (a color
 *    cast) until this is redone with real IQTune calibration.
 *  - luxRef LuxRef/Expo1/Lum1/Lum2/calibFactor: lux calibration constants.
 *
 * Everything else (AE algorithm enable, gamma, sensor delay, disabled
 * blocks) is generic/sensor-agnostic ISP behavior, kept as-is.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 ******************************************************************************
 */

#ifndef __IMX219_ISP_PARAM_CONF__H
#define __IMX219_ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for IMX219 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_IMX219 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 12,
        .BLCG = 12,
        .BLCB = 12,
    },
    .demosaicing = {
        .enable = 1,
        /* GRBG, not RGGB: the IMX219's native (no-flip) Bayer order is
         * RGGB, but the default build orientation (CMakeLists.txt
         * ORIENTATION=FRONT -> CAMERA_SELFY=1) applies a horizontal mirror
         * to the sensor (see SENSOR_IMX219_FLIP in app_cam.c ->
         * CMW_MIRRORFLIP_MIRROR -> IMX219_MIRROR), which shifts the CFA
         * phase by one column. Confirmed empirically: with RGGB declared
         * here, gain/color-matrix tuning couldn't touch a strong magenta
         * cast at all (even a neutral/identity matrix didn't help), which
         * only makes sense if demosaic itself was decoding the wrong
         * channels. If you rebuild with ORIENTATION=REAR (no mirror),
         * change this back to ISP_DEMOS_TYPE_RGGB. */
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "JudgeII-A", "JudgeII-TL84", "JudgeII-DAY", "Free Slot", "Free Slot", },
        .referenceColorTemp = { 2810, 4015, 6650, 0, 0, },
        .ispGainR = { 124000000, 182000000, 244000000, 0, 0, },
        .ispGainG = { 100000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 282000000, 212000000, 143000000, 0, 0, },
        .coeff = {
            { { 82450000, 90560000, -73010000, }, { -65469999, 181020000, -15559999, }, { -30490000, -52940000, 183430000, }, },
            { { 164670000, -20970000, -43700000, }, { -51330000, 178670000, -27339999, }, { -12490000, -48170000, 160670000, }, },
            { { 150570000, 2440000, -53010000, }, { -37350000, 193760000, -56420000, }, { -11100000, -35490000, 146590000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 61, 65, 30},
            { 46, 68, 37 },
            { 38, 68, 49 },
            { 0, 0, 0 },
            { 0, 0, 0 },
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    /* Centered half of the 1640x1232 frame (X0/Y0 = quarter, size = half),
     * same convention as IMX335's window over its own 2592x1944 frame. */
    .statAreaStatic = {
        .X0 = 410,
        .Y0 = 308,
        .XSize = 820,
        .YSize = 616,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 3,
    },
    .luxRef = {
        .HL_LuxRef = 1050,
        .HL_Expo1 = 5000,
        .HL_Lum1 = 20,
        .HL_Expo2 = 66644, /* IMX219_EXPOSURE_MAX */
        .HL_Lum2 = 117,
        .LL_LuxRef = 270,
        .LL_Expo1 = 9000,
        .LL_Lum1 = 10,
        .LL_Expo2 = 66644, /* IMX219_EXPOSURE_MAX */
        .LL_Lum2 = 36,
        .calibFactor = 0.905f,
    },
};

#endif /* __IMX219_ISP_PARAM_CONF__H */
