/**
 ******************************************************************************
 * @file    app_mnist.c
 *
 * MNIST digit classification (784-64-10 MLP) on a region of the camera frame.
 *
 * On user button press, the luma of a centered square region of interest
 * (ROI) is downscaled to 28x28 and classified. The ROI and a preview of the
 * last network input are drawn into the (YUY2) live view.
 *
 * Weights are generated by python-scripts/mnist_train.py.
 ******************************************************************************
 */
#include "app_mnist.h"

#include <assert.h>
#include <math.h>
#include <stdio.h>
  
#include "stm32n6xx_hal.h"
#ifdef STM32N6570_DK_REV
#include "stm32n6570_discovery.h"
#else
#include "stm32n6xx_nucleo.h"
#endif
#include "utils.h"
#include "mnist_weights.h"

#define MNIST_SIDE       28
#define MNIST_PIXELS     (MNIST_SIDE * MNIST_SIDE)
#define MNIST_HIDDEN     64
#define MNIST_CLASSES    10
/* after contrast stretch, values below are forced to background; tune for your lighting */
#define MNIST_THRESHOLD  0.35f
/* minimal max-min luma spread in the ROI, below it the ROI is considered empty */
#define MNIST_MIN_SPREAD 32
#define ROI_BORDER       2

struct roi {
  int x;
  int y;
  int size;
};

/* green in YUV (BT.601), drawn directly into the YUY2 frame */
static const uint8_t roi_color[3] = { 145, 54, 34 };

static volatile int classify_request;
static float last_input[MNIST_PIXELS];
static int has_last_input;

/* called from EXTI13 ISR via BSP_PB_IRQHandler() */
void BSP_PB_Callback(Button_TypeDef Button)
{
  if (Button == MNIST_BUTTON)
    classify_request = 1;
}

/* centered square, about half of the smaller side, multiple of 28 for integer downscale */
static struct roi roi_get(int width, int height)
{
  struct roi r;

  r.size = (MIN(width, height) / 2 / MNIST_SIDE) * MNIST_SIDE;
  r.x = ((width - r.size) / 2) & ~1; /* even x: YUY2 macropixel aligned */
  r.y = (height - r.size) / 2;

  return r;
}

/* Y channel of ROI -> box filter downscale -> invert -> contrast stretch -> [0,1] */
static void roi_extract(const uint8_t *frame, int width, struct roi r, float *out)
{
  const int s = r.size / MNIST_SIDE;
  uint8_t pix[MNIST_PIXELS];
  int lo = 255;
  int hi = 0;
  int ox, oy, dx, dy;
  int i;

  for (oy = 0; oy < MNIST_SIDE; oy++) {
    for (ox = 0; ox < MNIST_SIDE; ox++) {
      uint32_t sum = 0;

      for (dy = 0; dy < s; dy++) {
        const uint8_t *row = frame + ((r.y + oy * s + dy) * width + r.x + ox * s) * 2;
        for (dx = 0; dx < s; dx++)
          sum += row[dx * 2];
      }
      /* MNIST is a white digit on black: invert dark ink on white paper */
      i = oy * MNIST_SIDE + ox;
      pix[i] = 255 - sum / (s * s);
      lo = MIN(lo, pix[i]);
      hi = MAX(hi, pix[i]);
    }
  }

  for (i = 0; i < MNIST_PIXELS; i++) {
    float v = hi - lo >= MNIST_MIN_SPREAD ? (float)(pix[i] - lo) / (hi - lo) : 0.0f;

    out[i] = v < MNIST_THRESHOLD ? 0.0f : v;
  }
}

static int mlp_infer(const float *in, float *prob)
{
  float h[MNIST_HIDDEN];
  float sum = 0;
  float max;
  int best = 0;
  int i, j;

  for (j = 0; j < MNIST_HIDDEN; j++) {
    float acc = mnist_b1[j];

    for (i = 0; i < MNIST_PIXELS; i++)
      acc += mnist_w1[j][i] * in[i];
    h[j] = acc > 0 ? acc : 0;
  }

  for (j = 0; j < MNIST_CLASSES; j++) {
    float acc = mnist_b2[j];

    for (i = 0; i < MNIST_HIDDEN; i++)
      acc += mnist_w2[j][i] * h[i];
    prob[j] = acc;
    if (acc > prob[best])
      best = j;
  }

  /* softmax */
  max = prob[best];
  for (j = 0; j < MNIST_CLASSES; j++) {
    prob[j] = expf(prob[j] - max);
    sum += prob[j];
  }
  for (j = 0; j < MNIST_CLASSES; j++)
    prob[j] /= sum;

  return best;
}

static void print_input(const float *in)
{
  static const char shades[] = " .:-=+*#%@";
  int x, y;

  for (y = 0; y < MNIST_SIDE; y++) {
    for (x = 0; x < MNIST_SIDE; x++)
      putchar(shades[(int)(in[y * MNIST_SIDE + x] * 9.99f)]);
    putchar('\n');
  }
}

static void put_macropixel(uint8_t *frame, int width, int x, int y, const uint8_t yuv[3])
{
  uint8_t *p = frame + (y * width + x) * 2;

  p[0] = yuv[0];
  p[1] = yuv[1];
  p[2] = yuv[0];
  p[3] = yuv[2];
}

/* border lies just outside the ROI so it never ends up in the classifier input */
static void draw_roi(uint8_t *frame, int width, struct roi r)
{
  const int x0 = r.x - ROI_BORDER;
  const int x1 = r.x + r.size;
  int x, y;

  for (y = r.y - ROI_BORDER; y < r.y + r.size + ROI_BORDER; y++) {
    if (y < r.y || y >= r.y + r.size) {
      for (x = x0; x < x1 + ROI_BORDER; x += 2)
        put_macropixel(frame, width, x, y, roi_color);
    } else {
      put_macropixel(frame, width, x0, y, roi_color);
      put_macropixel(frame, width, x1, y, roi_color);
    }
  }
}

/* grey preview of the last network input, left of the ROI */
static void draw_preview(uint8_t *frame, int width, struct roi r)
{
  const int scale = (r.x - 2 * ROI_BORDER) / MNIST_SIDE;
  int x, y;

  if (scale < 1)
    return;

  for (y = 0; y < MNIST_SIDE * scale; y++) {
    for (x = 0; x < MNIST_SIDE * scale; x++) {
      uint8_t *p = frame + ((r.y + y) * width + x) * 2;

      p[0] = (uint8_t)(last_input[(y / scale) * MNIST_SIDE + x / scale] * 255.0f);
      p[1] = 128;
    }
  }
}

void MNIST_Init(void)
{
  float prob[MNIST_CLASSES];
  int ret;

  ret = BSP_PB_Init(MNIST_BUTTON, BUTTON_MODE_EXTI);
  assert(ret == BSP_ERROR_NONE);

  ret = mlp_infer(mnist_test_input, prob);
  printf("MNIST self test: predicted %d (%.1f %%), expected %d\n", ret, prob[ret] * 100.0f, MNIST_TEST_LABEL);
}

void MNIST_ProcessFrame(uint8_t *frame, int width, int height)
{
  const struct roi r = roi_get(width, height);
  const int32_t frame_size = width * height * 2;

  if (r.size < MNIST_SIDE)
    return;

  /* DCMIPP wrote this buffer by DMA: drop stale cache lines before the CPU touches it */
  SCB_InvalidateDCache_by_Addr(frame, frame_size);

  if (classify_request) {
    float prob[MNIST_CLASSES];
    uint32_t cycles;
    int digit;

    classify_request = 0;
    roi_extract(frame, width, r, last_input);
    has_last_input = 1;

    cycles = DWT->CYCCNT;
    digit = mlp_infer(last_input, prob);
    cycles = DWT->CYCCNT - cycles;

    print_input(last_input);
    /* CYCCNT counts CPU clock cycles */
    printf("MNIST digit: %d (%.1f %%) | %lu cycles | %.1f us @ %lu MHz\n", digit, prob[digit] * 100.0f,
           cycles, cycles * 1e6f / SystemCoreClock, SystemCoreClock / 1000000);
  }

  draw_roi(frame, width, r);
  if (has_last_input)
    draw_preview(frame, width, r);

  /* USB DMA reads the frame from memory: write the overlay back from cache */
  SCB_CleanDCache_by_Addr(frame, frame_size);
}
